function make_rootfs_config {
    
    ## type fedora / ubuntu
    local T=$1
    ## name fedora / ubuntu / apache ...
    local N=$2
    
    rootfs=/var/srvctl-rootfs/$N
    
    msg "Configure $rootfs"

    ## srvctl configuration related 
   
    mkdir -p $rootfs/usr/share/srvctl
    mkdir -p $rootfs/var/srvctl
    mkdir -p $rootfs/var/log/srvctl
    mkdir -p $rootfs/var/www/html
    
    setup_rootfs_ssh
    
## srvctl 
        ## add symlink to the srvctl application.
        ln -sf $install_dir/srvctl.sh $rootfs/bin/srvctl
        ln -sf $install_dir/srvctl.sh $rootfs/bin/sc

## NFS
    generate_exports $rootfs        

    ## enable nfs
    ln -s '/usr/lib/systemd/system/nfs.service' $rootfs'/etc/systemd/system/multi-user.target.wants/nfs.service'

    if [ $T == ubuntu ]
    then
       echo 'nameserver 10.10.0.1' > $rootfs/etc/resolvconf/resolv.conf.d/tail
       
       mkdir -p $rootfs/var/www/html
    fi
    
    if [  $T == fedora ]
    then
        ## make the installation smaller        
        rm $rootfs/usr/lib/locale/locale-archive
        ln -s /var/srvctl/locale-archive $rootfs/usr/lib/locale/locale-archive
    
        ## Container should be in the same timezone as the host.
        rsync -a /etc/localtime $rootfs/etc

    
    chroot $rootfs groupadd -r -g 101 srv
    chroot $rootfs useradd -r -u 101 -g 101 -s /sbin/nologin -d /srv srv
    
    chroot $rootfs groupadd -r -g 102 git
    chroot $rootfs useradd -r -u 102 -g 102 -s /sbin/nologin -d /var/git git
    
    #chroot ${rootfs_path} groupadd -r -g 103 node
    #chroot ${rootfs_path} useradd -r -u 103 -g 103 -s /sbin/nologin -d /srv node
    
    #chroot ${rootfs_path} groupadd -r -g 104 codepad
    #chroot ${rootfs_path} useradd -r -u 104 -g 104 -s /sbin/nologin -d /srv/etherpad-lite codepad
    
    #chroot ${rootfs_path} postalias /etc/aliases
    #chroot ${rootfs_path} 
    
    set_file $rootfs/etc/resolv.conf "# Generated by srvctl
search local
nameserver 10.10.0.1
"
        ## create selfsigned certificate
        cert_path=/var/srvctl-host/selfsigned-certificates/$N
        create_certificate $N
        
        ## add selfsigned certificate to container - for https reverse proxying
        cat $ssl_key > $rootfs/etc/pki/tls/private/localhost.key
        cat $ssl_crt > $rootfs/etc/pki/tls/certs/localhost.crt

    

## Apache 
    
        ln -s '/usr/lib/systemd/system/httpd.service' $rootfs'/etc/systemd/system/multi-user.target.wants/httpd.service'
    
        ## We disable lua by default
        ## taken from the apache page https://httpd.apache.org/docs/trunk/mod/mod_lua.html
        ## This module holds a great deal of power over httpd, which is both a strength and a potential security risk. 
        ## It is not recommended that you use this module on a server that is shared with users ...
        ## LoadModule lua_module modules/mod_lua.so
        rm -rf $rootfs/etc/httpd/conf.modules.d/00-lua.conf 
    
        set_file $rootfs/etc/httpd/conf.d/pound.conf '## srvctl
        <IfModule log_config_module>

            ### Custom log redefinition
            ## - with extra host header
            # LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %h %D \"%{Host}i\"" combined
            ## - As close as possible
            LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined

        </IfModule>

        Listen 8080
        Listen 8443 
'
    fi
}

