function make_rootfs_config {
    
    ## type fedora / ubuntu
    local T=$1
    ## name fedora / ubuntu / apache / codepad ...
    local N=$2
    
    local _fedora=false
    local _ubuntu=false
    local _apache=false
    
    if [ $T == fedora ]
    then
        _fedora=true
    fi
    if [ $T == ubuntu ]
    then
        _ubuntu=true
    fi

    
    rootfs=/var/srvctl-rootfs/$N
    
    msg "Configure $rootfs"

    ## srvctl configuration related 
   
    mkdir -p $rootfs/usr/share/srvctl
    mkdir -p $rootfs/var/srvctl
    mkdir -p $rootfs/var/log/srvctl
    mkdir -p $rootfs/var/www/html
    
    setup_rootfs_ssh
    
        ## srvctl 
        ## add symlink to the srvctl application.
        ln -sf $install_dir/srvctl.sh $rootfs/bin/srvctl
        ln -sf $install_dir/srvctl.sh $rootfs/bin/sc

    if $_fedora || $_ubuntu
    then
        ## NFS
        generate_exports $rootfs        
    fi

    if $_fedora
    then
        ## enable nfs
        ln -s '/usr/lib/systemd/system/nfs.service' $rootfs'/etc/systemd/system/multi-user.target.wants/nfs.service'
    fi
    
    
    if $_ubuntu
    then
       echo 'nameserver 10.10.0.1' > $rootfs/etc/resolvconf/resolv.conf.d/tail
    fi
       
    ## create selfsigned certificate
    cert_path=/var/srvctl-host/selfsigned-certificates/$N
    create_certificate $N
        
    if $_fedora
    then
        cat $ssl_key > $rootfs/etc/pki/tls/private/localhost.key
        cat $ssl_crt > $rootfs/etc/pki/tls/certs/localhost.crt  
    fi
    
    if $_ubuntu
    then
        cat $ssl_key > $rootfs/etc/ssl/private/localhost.key
        cat $ssl_crt > $rootfs/etc/ssl/certs/localhost.pem   
    fi    
    
    if $_fedora
    then
       
        set_file $rootfs/etc/resolv.conf "# Generated by srvctl
search local
nameserver 10.10.0.1
"
    fi
    
    if $_ubuntu
    then
        echo 'nameserver 10.10.0.1' >> $rootfs/etc/resolvconf/resolv.conf.d/base
    fi
    
    
    if $_fedora
    then

        ## make the installation smaller        
        rm $rootfs/usr/lib/locale/locale-archive
        ln -s /var/srvctl/locale-archive $rootfs/usr/lib/locale/locale-archive
    
        ## Container should be in the same timezone as the host.
        rsync -a /etc/localtime $rootfs/etc

    
    
    chroot $rootfs groupadd -r -g 101 srv
    chroot $rootfs useradd -r -u 101 -g 101 -s /sbin/nologin -d /srv srv
    
    chroot $rootfs groupadd -r -g 102 git
    chroot $rootfs useradd -r -u 102 -g 102 -s /sbin/nologin -d /var/git git
    
    #chroot $rootfs groupadd -r -g 27 mysql
    #chroot $rootfs useradd -r -u 27 -g 27 -s /sbin/nologin -d /var/lib/mysql mysql
    
    #chroot ${rootfs_path} groupadd -r -g 103 node
    #chroot ${rootfs_path} useradd -r -u 103 -g 103 -s /sbin/nologin -d /srv node
    
    #chroot ${rootfs_path} groupadd -r -g 104 codepad
    #chroot ${rootfs_path} useradd -r -u 104 -g 104 -s /sbin/nologin -d /srv/etherpad-lite codepad
    
    #chroot ${rootfs_path} postalias /etc/aliases
    #chroot ${rootfs_path} 
    
    fi
    
    ## Apache 
    local _pound_conf=/etc/httpd/conf.d/pound.conf
    
    if $_fedora
    then
    
        ln -s '/usr/lib/systemd/system/httpd.service' $rootfs'/etc/systemd/system/multi-user.target.wants/httpd.service'
    
        ## We disable lua by default
        ## taken from the apache page https://httpd.apache.org/docs/trunk/mod/mod_lua.html
        ## This module holds a great deal of power over httpd, which is both a strength and a potential security risk. 
        ## It is not recommended that you use this module on a server that is shared with users ...
        ## LoadModule lua_module modules/mod_lua.so
        rm -rf $rootfs/etc/httpd/conf.modules.d/00-lua.conf 
    
    fi
    
    if $_ubuntu
    then
        chroot ${rootfs_path} /lib/systemd/systemd-sysv-install enable apache2
 
        _pound_conf=/etc/apache2/conf-available/pound.conf
        ln -s /etc/apache2/conf-available/pound.conf $rootfs/etc/apache2/conf-enabled/pound.conf
    fi

        set_file $rootfs/$_pound_conf '## srvctl
        <IfModule log_config_module>

            ### Custom log redefinition
            ## - with extra host header
            # LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %h %D \"%{Host}i\"" combined
            ## - As close as possible
            LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined

        </IfModule>

        Listen 8080
        Listen 8443 
'
    
}

